_wandb:
    value:
        cli_version: 0.23.0
        e:
            1gya9vwrxa7lsbyb96q6nol08leq9kvo:
                args:
                    - --epochs
                    - "10"
                    - --batch-size
                    - "32"
                codePath: pytorch_test/ResNet50_CIFAR
                codePathLocal: ResNet50_CIFAR
                cpu_count: 156
                cpu_count_logical: 156
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2059780689920"
                        used: "246790836224"
                email: spall.philipp@web.de
                executable: /home/phsp/uv-env/bin/python
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-9b07c690-490e-ccc0-3b86-d706e0621fd5
                host: vm-compute
                memory:
                    total: "540764688384"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.39
                program: /home/phsp/thesis/pytorch_test/ResNet50_CIFAR
                python: CPython 3.12.3
                root: /home/phsp/thesis/pytorch_test
                slurm:
                    cluster_name: (null)
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: default
                    job_cpus_per_node: "8"
                    job_end_time: "1764076958"
                    job_gid: "1016"
                    job_gpus: "1"
                    job_id: "253"
                    job_name: resNet_Cifar
                    job_nodelist: vm-compute
                    job_num_nodes: "1"
                    job_partition: main
                    job_qos: normal
                    job_start_time: "1764073358"
                    job_uid: "1016"
                    job_user: phsp
                    jobid: "253"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: vm-compute
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /home/phsp/thesis
                    submit_host: vm-compute
                    task_pid: "1590585"
                    tasks_per_node: "1"
                    topology_addr: vm-compute
                    topology_addr_pattern: node
                    tres_per_task: cpu:8
                startedAt: "2025-11-25T12:22:43.165820Z"
                writerId: 1gya9vwrxa7lsbyb96q6nol08leq9kvo
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 3
                - 16
                - 17
                - 61
            "4": 3.12.3
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 128
device:
    value: cuda
epochs:
    value: 10
learning_rate:
    value: 0.1
torch_compile:
    value: max-autotune
